### ISSUE TITLE
Dim the screen instead of brightening it

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#10]
In the Windows version, the screen is brightened when any menu is brought up.

In Android, a smaller screen makes yellow-on-white (or on top of very bright/pale colors) harder to read. Dimming the screen instead might make the yellow text easier to read.

**Comment by VectorSatyr** [comment]
I believe this should apply to all versions. What say you, @overbound ?

**Comment by AlexKhayrullin** [comment]
Reassigned to @overbound just for the question? :)

(if it only needs to be done on Android, please reassign back to me)

**Comment by AlexKhayrullin** [comment]
BTW, I just tried it (see screenshots here: https://twitter.com/AlexKhayrullin/status/922183527709532161 ) , and it looks so much better ^^

**Comment by VectorSatyr** [comment]
@AlexKhayrullin Overbound isn't going to respond. Just go ahead and change this to a general issue.

**Comment by overbound** [comment]
I think its a great improvement go for it!

**Comment by AlexKhayrullin** [comment]
Thanks :) .
It's done in the Android compatibility branch.
