### ISSUE TITLE
Some visual effects not working properly on Android

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#11]
This is a big one.

Some special effects that make use of either shaders or some draw modes (didn't look into it yet) don't work properly on Android, and might not work on other platforms the game might be ported to. So far, I've seen two clear cases:

- The wave on the title screen, while the names of developers and contributors are listed, is either all white, or only parts of it are visible.
- The visual effect when switching time periods is also messed up: when it covers the screen on the first map, it's all white, and when it leaves the screen on the second map, it's all black.

So, to resolve this, this is what needs to be done:

- Once all the other developments are done, and the port is 100% playable (because I absolutely need to test it on hardware) , make a list of all the visual effets that are messing up.
- Try to find the common cause, if any. See if it can be easily fixed.
- Maybe design and implement alternative, simpler, visual effects. I don't think I will be able to do this one alone.

**Comment by overbound** [comment]
This may be a bug in Game Maker Studio. Via: [Here](https://forum.yoyogames.com/index.php?threads/shader-support.21878/)

If all else fails I will replace the effects static animations. But I will wait to resolve this issue until the port is nearly complete.

**Comment by AlexKhayrullin** [comment]
Yes, I absolutely agree, it needs to be done at the very end of the development of the port, so there's no emergency here. Just something to keep in mind.

Also, I'd say that these newer, simpler animations absolutely should not replace those that are already in place. My rationale is this: if the default effects work as expected on a platform the game is being ported to, then use them; if they don't, use simpler animations, maybe implement a script "are_animations_supported()" that returns true or false depending on the platform, and work from there? I would absolutely hate to replace the very good looking effects that are already in place with simpler ones on platforms that don't need this switch...

**Comment by overbound** [comment]
Agreed we can check the OS before determining which one to use.

**Comment by AlexKhayrullin** [comment]
As I know nothing about shaders, I decided to do much simpler effects. There are three times where the Time Travel shader appears:

- During the rundown of the game's creators before the title screen: replaced the background with the wave by a black background.
- While time travelling in a level: a simple quick fade to white.
- During the cinematic where Metal Sonic catches up to the team in the past: one white flash at the beginning of the sound effect, and another one when Metal Sonic appears (this one is in progress) .

I know that these aren't perfect alternatives, but they look quite serviceable.

I can confirm that the Time Travel shader is the only visual effect not supported on Android.
