### ISSUE TITLE
Use a surface for drawing Dpad on Android

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#110]
Right now, the Dpad and especially the two-directional Dpad-looking thing in Special Stages clearly look like two semi-transparent sprites overlayed on top of each other.

Need to change the way they are drawn, so that the base is not visible under the joystick, yet both elements can be made semi-transparent as if they were one.

**Comment by nkrapivin** [comment]
On some very low-end phones the game may run out of video memory, and surface_set_target is pretty slow on Android.
So I think this should be togglable if it's going to be implemented.

**Comment by AlexKhayrullin** [comment]
OK, I'll close it since it's not as necessary as previously thought (the transparency thing would be mostly obscured by the player's thumb anyway).
