### ISSUE TITLE
Gamepad mapping softlock on mobile

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#117]
Reported by @romulok77 : the mapping screen locks on the "Mapping is incomplete" box.

**Comment by AlexKhayrullin** [comment]
I could not reproduce.
I'm leaving this open in case there are new details that come up, but removing the issue from the milestone.

**Comment by romulok77** [comment]
in the released version this no longer occurs. For some reason the error only occurred when testing the game on GM. So there is nothing more to add, better to close this problem.

**Comment by AlexKhayrullin** [comment]
OK, thanks :)
