### ISSUE TITLE
Jingles conflict

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#126]
When a character is invincible and grabs a life, no music plays after the "life get" between the moment when the jingle finishes and when the invincibility runs out.

Both are considered to be "jingles" by the game, so there might be some conflict there.

**Comment by nkrapivin** [comment]
The +1 life sound is an `effect`, and invincibility is a `jingle`.
Also how does one reproduce this? I've added this debug code:
```gml

if (keyboard_check_pressed(vk_f6)) {
    // icon box
    with objPlayer player_get_invincibility();
}
else if (keyboard_check_pressed(vk_f7)) {
    // rings
    player_get_lives(1);
}
```

And here's a video https://youtu.be/66iU2kvrlnk
