### ISSUE TITLE
VVZ Act 1 Past's end and VVZ Act 2 Past's beginning do not match

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#127]
The background at the right edge, where the bridge is, has tiles in the background in Act 2, but not in Act 1, so the room switch becomes fairly obvious.

The tileset of VVZ Act 1 Past must be updated to include them.

**Comment by VectorSatyr** [comment]
@AlexKhayrullin Screenshot for reference?

**Comment by AlexKhayrullin** [comment]
@VectorSatyr Sure, sorry.

Act 1 ends:
![1610238006445](https://user-images.githubusercontent.com/2079839/104111449-80b36f00-52ea-11eb-88ca-d08ca6f24340.jpg)

Act 2 begins:
![1610238006439](https://user-images.githubusercontent.com/2079839/104111457-90cb4e80-52ea-11eb-99df-90f31117cd4a.jpg)
