### ISSUE TITLE
Softlock with Super Sonic on Tornado in Drifting Dynamo

### ISSUE THREAD

**Issue by overbound** [overbound/SonicTimeTwisted#129]
Walking into the flying enemies as SS offsets him a bit too much to either fall off or touch the propeller.
![image](https://user-images.githubusercontent.com/32524065/104113942-59e24200-52c4-11eb-9c82-6764a2561de5.png)

Per@AmberCyprian on Twitter https://twitter.com/AmberCyprian/status/1348108898092392448

**Comment by AlexKhayrullin** [comment]
Related to https://github.com/overbound/SonicTimeTwisted/issues/30 ?

**Comment by AlexKhayrullin** [comment]
A related issue is after arriving at the plane's rightmost position and jumping down, it is possible by jumping through the wing several times, to let the plane go past its right bound. As an added bonus, whenever the character is on the ground after this, the plane "thinks" the character is back on the wing and the gamepad rumbles.

The behavior of the plane should be revised :/ .

**Comment by AlexKhayrullin** [comment]
Might also take care of #30
