### ISSUE TITLE
Pre-Boss Music Cutout Bug

### ISSUE THREAD

**Issue by bennascar** [overbound/SonicTimeTwisted#136]
Before a boss in Time Twisted, the music cuts out. However, when you seem to get a 1-up during this period of the music being cut out, such as from rings drawn from an Thunder Shield, the music will continue on again like it normally would.

**Comment by nkrapivin** [comment]
Hi. Can you please elaborate and tell the name of the boss where you were able to repro the issue?

**Comment by AlexKhayrullin** [comment]
Tested in AAZ act 2 after Nik's refactoring: now the "life get" jingle also cuts out.
