### ISSUE TITLE
Change the speed of the score tally

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#14]
(suggested by Hinchy)

The countdowns on the "Act clear" score tallies must be sped up or slowed down, depending on the acquired bonuses (mostly sped up :) ) , so that the end of the countdown occurs at the exact moment when the cash register sound is heard.

**Comment by VectorSatyr** [comment]
The way the score tally was originally designed is that instead of the values counting down, the digits would be shuffled randomly until the "chime" sound was made, and then the final values would be displayed. I think re-implementing this behavior would work best.

**Comment by AlexKhayrullin** [comment]
I'm sorry, I don't exactly understand...

Do you mean that after the chime, the tally still has to start counting down?

**Comment by VectorSatyr** [comment]
There is no "count down". The numbers on the score tally are randomized until the "chime" sound hits, and then the final numbers are shown.

**Comment by AlexKhayrullin** [comment]
I am so sorry, I am still struggling to visualize this. Is this the idea:

- At first, the ring and time bonuses are displayed, as well as the perfect bonus if applicable, the score has not been updated yet.
- Then, after a pause, random digits start appearing in front of all of the labels, including the score.
- After the chime is heard, the bonuses' values are set to 0, the score is updated.

Is that what you mean?

Again, so sorry.

**Comment by VectorSatyr** [comment]
That is exactly what I mean.

**Comment by AlexKhayrullin** [comment]
Great, thanks!

Now that I've found and understood the code that manages this, I'm actually thinking of implementing both proposed methods (slowdown/speedup and the random digits) and allowing the player to select one of them in the options menu. That way, both Hinchy and you will get what you ask :) .

**Comment by AlexKhayrullin** [comment]
@VectorSatyr can you please check out the branch "feature/android-compatibility", set the option "Score tally mode" to "random digits", try completing an act or a special stage and tell me if that what you had in mind?

**Comment by VectorSatyr** [comment]
"Random Digits" works close enough to what I was expecting. In the original, the numbers don't shrink, but instead remain their original digit count until the end, but this is fine.

**Comment by AlexKhayrullin** [comment]
I took your comment into account: the two (or three) bonuses now show a constant number of digits based on their initial value, and the total now has a constant number of digits based on its final value.
