### ISSUE TITLE
Super Sonic Transformation with Shield

### ISSUE THREAD

**Issue by bennascar** [overbound/SonicTimeTwisted#140]
When you transform as Super Sonic while holding a shield, you actually don't transform beyond sprites. You can still lose your shield and your rings. They don't drain down either. No properties of the actual transformation are applied beyond changing Sonic's sprites to his Super counterpart. 
![image](https://user-images.githubusercontent.com/77413850/104515248-88139a80-55c0-11eb-8924-c8feb9efed72.png)

**Comment by AlexKhayrullin** [comment]
After testing a bit, it's not a matter of having a shield or not, but Sonic indeed does not-really-transform after the timer hits 10:00:00.
