### ISSUE TITLE
[SUGGESTION] Will there be Linux builds?

### ISSUE THREAD

**Issue by RoloDeOvo** [overbound/SonicTimeTwisted#141]
I know that it's possible to export to Linux with Game Maker Studio, but the software itself is prohibitively expensive (At least here in Brazil, it is.) and most people aren't gonna be willing to pay for an entire game development suite to export one game anyway.

I tried Wine but the game doesn't run too well through it. It can't compile the TimeTravel shader and the WaveShader makes the game crash.

**Comment by AlexKhayrullin** [comment]
I can try exporting a Linux build for the bugfix version I'm preparing, but it will be a Ubuntu package, because that's all Game Maker Studio can export.

**Comment by AlexKhayrullin** [comment]
Done by @nkrapivin
