### ISSUE TITLE
PT-BR zone names

### ISSUE THREAD

**Issue by romulok77** [overbound/SonicTimeTwisted#144]
To complete the translation in PT-BR I made these translations for the name of the zones, I used the model of Alex's file to store this information, so please take a look and if someone from Brazil here wants to help with the names, I appreciate it.

Here: Https://drive.google.com/file/d/1dlYXoXYO7vukD5uf2GHXqEt2EwKY1fGX/view?usp=drivesdk

**Comment by AlexKhayrullin** [comment]
A couple of guidelines:

- Obviously, keep the names relevant to the zones' content.
- Depending on the language, the "Zone" part can be either at the start of a zone name, or at the end, but it cannot change from one zone to another, at least not at this moment (for instance, all zones in any given language are either called something like "zone of WORD1 WORD2" or "WORD1 WORD2 zone") . If it is possible to pick a lane once and for all, great. If not, you should submit a separate issue, asking for the "titlecard_zone_is_first" flag to be zone-specific. What this flag does is make sure the "zone" part of a zone name is typed in a smaller font on title cards.
- As the game is a fan sequel/alternate continuity to Sonic CD, the zone names are all alliterations (two words starting with the same letter) , and first letters don't repeat.

Good luck with the last one, it's the hardest one to follow :)
