### ISSUE TITLE
Manage a default "back" key

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#18]
Every platform will now have a default "back" key which will allow to do the following:

- Pause the game when allowed (no matter the used input device and no matter which key is mapped as "START", this one serves as a backup) .
- In a menu, if the current screen has a "back" item, activate it.
- Cancel a keyboard/gamepad mapping in progress. Consequently, this key can't be mapped.

This will mostly be useful in Android, as it is possible to start a game after having selected an input device (BT keyboard, BT gamepad) which isn't currently connected, or which may turn off or become otherwise unavailable during the game.

On Windows, the key is "Escape". On Android, it is the "Back" button, which Game Maker Studio considers as being equivalent to "Backspace".

While the code to cancel keymappings in progress is already in place, the rest of it (pause, "back") isn't.

**Comment by VectorSatyr** [comment]
By "Back" key on Android do you mean the back _button_ on a typical Android device?

**Comment by AlexKhayrullin** [comment]
Yes

**Comment by overbound** [comment]
This sounds like another good improvement.
