### ISSUE TITLE
Unable to find any instance for object index '147784' name '<undefined>'

### ISSUE THREAD

**Issue by overbound** [overbound/SonicTimeTwisted#185]
Bug found when using Lighting Shield in Drifting Dynamo. Checking references exist before using them in Step event of objRingMagnetized should fix this.

Found this bug on Drifting Dynamo:
___________________________________________

############################################################################################

FATAL ERROR in

action number 1

of  Step Event0

for object objRingMagnetized:

Unable to find any instance for object index '147784' name '<undefined>'

at gml_Object_objRingMagnetized_Step_0

############################################################################################
___________________________________________
I'm on version 1.0.4, not sure if it's an old bug or not!

**Comment by AlexKhayrullin** [comment]
Fixed in 1.1.0.
