### ISSUE TITLE
Level select and the regular menu appearing at once

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#19]
During my tests with the BT keyboard, I pressed random keys during startup and somehow managed to activate both the level select and the main menu at once, despite them being completely different states in the object objMenu. Both were shown at once, and both were unusable.

Need to look into this...

**Comment by VectorSatyr** [comment]
Could it be that more than 1 objMenu was instantiated, somehow?

**Comment by AlexKhayrullin** [comment]
Looks like it :/ . But since it is only instantiated during the create event of objTitleControl, this might be a sign of a bigger problem, at least with the Android version.

At least it might explain why I'm still having slowdowns when the game starts.

**Comment by AlexKhayrullin** [comment]
It appears that this is a regression in the Android builds: the Android version of the "objMenu" object sometimes somehow appears at the same time as the default version of "objMenu".

I could consistently reproduce it on Android by displaying the menu and accessing the options after starting a new game and proceeding to Attraction Attack Act 2.
