### ISSUE TITLE
When a character runs on water, there is a pixel between the water surface and the water trailing effect

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#201]
All is said.

A small graphical issue, noticeable as soon as AAZ Act 1.

**Comment by romulok77** [comment]
true, but that doesn't happen when playing with tails, only with sonic and knuckles

**Comment by AlexKhayrullin** [comment]
II fixed it for everyone by making the y ccoordinate of the splash dependant on the water level, and not on the character's y coordinate.
