### ISSUE TITLE
Change the way colored text is handled in score cards.

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#204]
Because of the way colored text is handled in score cards (first the normal text is drawn, then the game puts the character's colored name on top of it) , the player character's name can only be at the beginning of a message. This is reportedly a blocking issue for a German translation.

Same applies for the text about becoming Super Sonic.

There should be a way to place tags around text that should be colored instead.

**Comment by nkrapivin** [comment]
Is implemented in the merged `tr-it` branch.
