### ISSUE TITLE
Special Stage Error on large screens in mobile port

### ISSUE THREAD

**Issue by Herobrine100x** [overbound/SonicTimeTwisted#208]
The screen isn't cleared correctly on the sides on my phone (I have a Samsung Galaxy S10)

**Comment by nkrapivin** [comment]
Do you have a screenshot of the moment when garbage is present on the screen?

**Comment by Herobrine100x** [comment]
I don't have the S10 anymore.

**Comment by AlexKhayrullin** [comment]
I had some garbage on my tablet (Samsung Galaxy S7) one time, but I have no idea how to reproduce it reliably.

**Comment by AlexKhayrullin** [comment]
![Screenshot_2022-02-19-15-17-38-549_com overboundstudio SonicTimeTwisted](https://user-images.githubusercontent.com/2079839/154803273-f10b8b31-62d0-488b-b025-b018ea7e78b1.jpg)

Just had this happen in Special Stage 2 Past

**Comment by AlexKhayrullin** [comment]
Fixed thanks to pointers from Nik: two maps didn't have the "Clear Display Buffer" flag enabled.
