### ISSUE TITLE
Investigate Frigid Fortress Act 1 Slowdown

### ISSUE THREAD

**Issue by overbound** [overbound/SonicTimeTwisted#24]
Frigid Fortress Act 1 Future and especially the past seem to be more resource intensive than the rest of the game. This should investigated and solved. 

Potential Causes:
- Abnormally large number of instances?
- Abnormally large number of tiles?
- Mole walking movement is cpu intense?

**Comment by AlexKhayrullin** [comment]
According to the profiler, it is indeed an enemy causing the slowdown, but not the one you think:

![image](https://user-images.githubusercontent.com/2079839/38835748-4b69987e-41cc-11e8-90ea-c892868d14a7.png)

**Comment by AlexKhayrullin** [comment]
I can confirm this is indeed a huge problem: I've been playtesting the Android build on my Xiaomi A1 (a rather recent and quite powerful device) . The first two zones and FF Act 1 Present worked flawlessly, but FF Act 1 Past brought it down to its proverbial knees.

**Comment by AlexKhayrullin** [comment]
Recoded slightly the sealbot's behavior so that it only ever activated when the player is around. It helps a lot.
