### ISSUE TITLE
30FPS Support?

### ISSUE THREAD

**Issue by MysticAx0lotl** [overbound/SonicTimeTwisted#273]
Hello! I'm working on trying to port this game to the PS Vita, and while the port runs, it's rather laggy. I have come to the conclusion that if I make the game run at 30FPS, I'd see a major performance boost. Does this game have 30FPS support built-in, or is that something I'll have to add? If so, what's the best way to do that? Thanks!

**Comment by AlexKhayrullin** [comment]
There was a time when I thought adding 30FPS support would help out with performance on Android too. I ended up rolling everything back because the performance boost was not as good as I expected it to be.

So: no, you can deactivate drawing every other frame on a global level, but a lot of objects would need to be tweaked one by one to make sure they flash corrrectly, as opposed to staying constantly visible or constantly invisible.

**Comment by MysticAx0lotl** [comment]
> you can deactivate drawing every other frame on a global level, but a lot of objects would need to be tweaked one by one to make sure they flash corrrectly, as opposed to staying constantly visible or constantly invisible.
>
What function would I modify to do that? After 20 minutes of searching, I found nothing.

**Comment by AlexKhayrullin** [comment]
You can do something like this ("enable_draw" is a boolean), I don't remember which event would be the best for this, but it should run on every Step:
```
enable_draw = !enable_draw;
draw_enable_drawevent(enable_draw);
```

**Comment by MysticAx0lotl** [comment]
> You can do something like this ("enable_draw" is a boolean), I don't remember which event would be the best for this, but it should run on every Step:
> ```
> enable_draw = !enable_draw;
> draw_enable_drawevent(enable_draw);
> ```

Sorry for not being clear, I meant in which script file does the code reside? (Thanks for your help so far btw)

**Comment by AlexKhayrullin** [comment]
It was a special separate object that doesn't exist anymore.

**Comment by MysticAx0lotl** [comment]
> It was a special separate object that doesn't exist anymore

So how would I go about implementing that in the current codebase?

**Comment by MysticAx0lotl** [comment]
(I should make it clear that I don't have the Gamemaker 1.4 IDE. I'm having to use Notepad++ for this project)

**Comment by AlexKhayrullin** [comment]
Oh. If you don't have the IDE, then it will be really hard to properly implement it.
I guess you could try adding the script to objScreen somewhere or see this: https://github.com/overbound/SonicTimeTwisted/blob/dafb525a986a8a51ef11442363a84848e1ef4c90/SonicTimeTwisted.gmx/objects/objFramerate.object.gmx , but again, that's only a small part. You'd need to make sure all flashing objects flash correctly in both 30FPS and 60FPS by editing them one by one.

**Comment by MysticAx0lotl** [comment]
[objFramerate.object.gmx.txt](https://github.com/overbound/SonicTimeTwisted/files/8374296/objFramerate.object.gmx.txt)
So something like this? Just to get me started?

**Comment by MysticAx0lotl** [comment]
[objScreen.object.gmx.txt](https://github.com/overbound/SonicTimeTwisted/files/8374317/objScreen.object.gmx.txt)
I also hardcoded 30FPS into the Screen object. It's compiling, here's hoping it won't crash.

**Comment by AlexKhayrullin** [comment]
You can use the object that I linked you to to get started, yours seems to have redundant code (you don't need "enable_draw" if you already have "skip", they do the same thing) .

I can't run GameMaker Studio at the moment (working on another project on Linux) , so I'm sorry, I can't guide you further than this..

**Comment by MysticAx0lotl** [comment]
> You can use the object that I linked you to to get started, yours seems to have redundant code (you don't need "enable_draw" if you already have "skip", they do the same thing) .
> 
> I can't run GameMaker Studio at the moment (working on another project on Linux) , so I'm sorry, I can't guide you further than this..

Gotcha. You've been extremely helpful, thanks! Closing for now, I'll reopen if I have any more questions. Take care!
