### ISSUE TITLE
[PSVita?] Could Not Compile Time Travel Shader

### ISSUE THREAD

**Issue by MysticAx0lotl** [overbound/SonicTimeTwisted#274]
When launching the game, I get a dialogue box that says "Could Not Compile Time Travel Shader". I haven't tested far enough to see if this affects gameplay at all. This may also be the cause of my PS Vita port crashing the GPU when I try to time travel.

**Comment by VectorSatyr** [comment]
Do you have the proper DirectX runtimes?

From the README:

> If DirectX Drivers are missing you may see the the following error upon launching the game:

```
############################################################################################
FATAL ERROR in Vertex Shader compilation
ShaderName: TimeTravelShader

D3DXCompile failed - result

at gml_Object_objTitleLighting_Create_0
############################################################################################
```

> Download DirectX 9.0c runtimes from Microsoft to fix this (links may change)
> Full Download - https://www.microsoft.com/en-us/download/details.aspx?id=34429
> Web Installer - https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=35

**Comment by MysticAx0lotl** [comment]
> Do you have the proper DirectX runtimes?
>
No, I was using a fresh Windows install lol. That would explain why time travelling crashes on the Vita. To work around this, I tried cloning the Android config and naming it to "psvita.config.gmx", and replacing all references to Android in the main gmx with references to the PS Vita. GMaker compiled it, let's see if it works!

**Comment by nkrapivin** [comment]
> > Do you have the proper DirectX runtimes?
> 
> No, I was using a fresh Windows install lol. That would explain why time travelling crashes on the Vita. To work around this, I tried cloning the Android config and naming it to "psvita.config.gmx", and replacing all references to Android in the main gmx with references to the PS Vita. GMaker compiled it, let's see if it works!

On PSVita you MUST, you HAVE, you are REQUIRED to use the `PlayStation` config. Or else savedata won't be asynchronous and other issues may arise. Can you capture the app's log with ShipLog or PrincessLog?

**Comment by nkrapivin** [comment]
Also it seems that you're lacking the confidential Sony tool known as psp2cgc to compile PSVita shaders, find a proper PSVita SDK with all the tools and build the game again :*

**Comment by MysticAx0lotl** [comment]
> Also it seems that you're lacking the confidential Sony tool known as psp2cgc to compile PSVita shaders, find a proper PSVita SDK with all the tools and build the game again :*

I do have psp2cgc, and I compiled the game using it, but it still crashes the GPU when I compiled the game.

**Comment by MysticAx0lotl** [comment]
> > > Do you have the proper DirectX runtimes?
> > 
> > 
> > No, I was using a fresh Windows install lol. That would explain why time travelling crashes on the Vita. To work around this, I tried cloning the Android config and naming it to "psvita.config.gmx", and replacing all references to Android in the main gmx with references to the PS Vita. GMaker compiled it, let's see if it works!
> 
> On PSVita you MUST, you HAVE, you are REQUIRED to use the `PlayStation` config. Or else savedata won't be asynchronous and other issues may arise. Can you capture the app's log with ShipLog or PrincessLog?

Ohhh... OK. The problem is that G*Maker passes the platform=psvita argument when compiling the game. Any idea how to change it?

As for the log, I can send it when I start the project again (sometime in May).

**Comment by nkrapivin** [comment]
> > > > Do you have the proper DirectX runtimes?
> > > 
> > > 
> > > No, I was using a fresh Windows install lol. That would explain why time travelling crashes on the Vita. To work around this, I tried cloning the Android config and naming it to "psvita.config.gmx", and replacing all references to Android in the main gmx with references to the PS Vita. GMaker compiled it, let's see if it works!
> > 
> > 
> > On PSVita you MUST, you HAVE, you are REQUIRED to use the `PlayStation` config. Or else savedata won't be asynchronous and other issues may arise. Can you capture the app's log with ShipLog or PrincessLog?
> 
> Ohhh... OK. The problem is that G*Maker passes the platform=psvita argument when compiling the game. Any idea how to change it?
> 
> As for the log, I can send it when I start the project again (sometime in May).

The tool you're using doesn't let you choose a specific project configuration, just don't use it :p
I don't do that, there are plenty of ways to mess with the engine directly.

**Comment by MysticAx0lotl** [comment]
> > > > > Do you have the proper DirectX runtimes?
> > > > 
> > > > 
> > > > No, I was using a fresh Windows install lol. That would explain why time travelling crashes on the Vita. To work around this, I tried cloning the Android config and naming it to "psvita.config.gmx", and replacing all references to Android in the main gmx with references to the PS Vita. GMaker compiled it, let's see if it works!
> > > 
> > > 
> > > On PSVita you MUST, you HAVE, you are REQUIRED to use the `PlayStation` config. Or else savedata won't be asynchronous and other issues may arise. Can you capture the app's log with ShipLog or PrincessLog?
> > 
> > 
> > Ohhh... OK. The problem is that G*Maker passes the platform=psvita argument when compiling the game. Any idea how to change it?
> > As for the log, I can send it when I start the project again (sometime in May).
> 
> The tool you're using doesn't let you choose a specific project configuration, just don't use it :p I don't do that, there are plenty of ways to mess with the engine directly.

The problem is that I don’t have a Gamemaker license, and there’s no way to get one (not even illegitimately)
