### ISSUE TITLE
add analog control option to joystick in special stages

### ISSUE THREAD

**Issue by poyribn** [overbound/SonicTimeTwisted#278]
the special stages have an analog control option when using the phone's gyroscope, so i can't see why the joystick of the USB/BL controller doesn't have an analog option for special stages.

i find the "simulate button" 
joystick controls for special stages a bit uncomfortable, so i would like to try the analog option, which is unfortunately not in the game.

**Comment by RinMaru** [comment]
is has joystick support unless you're not using a xinput controller then idk

**Comment by poyribn** [comment]
i can use joystick, but only in digital mode.
the point of this issue is that only digital input is supported from joystick, but the option to use analog input instead in the special stages should be supported too for joystick.

**Comment by AlexKhayrullin** [comment]
Why not, might as well try :)
