### ISSUE TITLE
Android app isn't compatible with your phone, Pixel 7, Android 13

### ISSUE THREAD

**Issue by rubin110** [overbound/SonicTimeTwisted#281]
Thanks for making this fan game. I tried loading the APK offered off of itch.io, however when I do the install on my Pixel 7 running Android 13 I get an error that the app isn't compatible with my phone. I'm not sure what Android API this APK was built with.

**Comment by AlexKhayrullin** [comment]
Unfortunately, due to API incompatibilities and GameMaker 1.4.9999 obviously no longer being updated, it is impossible to implement the support of newer phones in Sonic Time Twisted 1.x.

Sonic Time Twised 2.0.0, which has just started development, will be compatible though.
