### ISSUE TITLE
Steam Deck + Windows: Timer causing display issues

### ISSUE THREAD

**Issue by veesonic** [overbound/SonicTimeTwisted#282]
I am playing on the Steam Deck with Windows and it appears that the game is causing display issues. From what I can tell the score timer at the top left runs very fast and the last digit is causing some pixelation. This persists even after restarting. I noticed that playing other games will eventually fix it but I'm concerned about long term damage to the display.

Steps To Reproduce:
1. Start the game. (When the issue happens the video settings are set to full screen)
2. Play for a bit.
3. Exit the game and observe the Steam Deck screen.

Device: Steam Deck (512 gb)
OS: Windows
Game Version: 1.1.2

![20230629_105824](https://github.com/overbound/SonicTimeTwisted/assets/63419981/7603cdbf-e1ac-4267-b0a2-384f197e24c8)

![20230629_105829](https://github.com/overbound/SonicTimeTwisted/assets/63419981/0a2ff1bb-67f5-422e-9c02-5b7c4096844b)

In the image above note the appaearance above the Rockstar icon.

**Comment by AlexKhayrullin** [comment]
Hi.

Thanks for reporting this.

I'm planning on making a minor update, I'm taking this into account.

I suppose that an option to hide the centiseconds in the timer, making it simply "MINUTES:SECONDS" would do the trick, yeah?

**Comment by veesonic** [comment]
Yeah I think thats a good workaround. An option like that can prevent this issue. 😄

**Comment by AlexKhayrullin** [comment]
Implemented for the next update:

![image](https://github.com/overbound/SonicTimeTwisted/assets/2079839/81d1da82-3af7-400a-80df-effcd5a8c541)
![image](https://github.com/overbound/SonicTimeTwisted/assets/2079839/6b4b85f0-b73f-44e3-831e-04dcc617a8a3)
