### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [overbound/SonicTimeTwisted#303]
https://github.com/search?q=repo%3Aoverbound%2FSonicTimeTwisted%20any%20later&type=code
says GPLv3-or-later, whereas
https://hosted.weblate.org/projects/sonic-time-twisted/game-release-2-0/#information
says GPLv3-only

It can be changed in
https://hosted.weblate.org/settings/sonic-time-twisted/game-release-2-0/
and
https://hosted.weblate.org/settings/sonic-time-twisted/glossary/

**Comment by AlexKhayrullin** [comment]
Updated.

Also, the correct website (and repo) is https://github.com/overbound/SonicTimeTwisted2.0 with the "2.0" at the end. My bad, I changed that too in the project's properties.
