### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#4]
Test the BT gamepad support (regular gamepad & iCade) .
Implement it if it is missing.

**Comment by AlexKhayrullin** [comment]
Looks like there's still stuff to do on this front: the gamepad I have worked on the button configuration menu, but not at all in the game itself... weird.

**Comment by AlexKhayrullin** [comment]
A native Android class has been created to read bluetooth keyboard & gamepad input.

It works in a simple app that dumps the state of all currently detected inputs, and works 100% as intended! Joy :) ! I still need to properly plug it in into the Sonic Time Twisted GMS project and to make sure its inclusion neither influences the Windows version, nor slows things down with constant "if OS = Android" checks.

**Comment by AlexKhayrullin** [comment]
Reopened the issue, as the library turned out to be a horror performance-wise.
I'll be rewriting it.

**Comment by nkrapivin** [comment]
Tried out https://github.com/overbound/SonicTimeTwisted/commit/fd5e511ae890d7648f57d1648295d914a23be3ae
Phone: Xiaomi Redmi 6A, Android 9, MIUI Global Stable 11.0.8.0
Gamepad: Sony DualShock 4 V2 (that comes with PS4 Slim/Pro)

Works fine, except a few issues:
- For some reason controls don't save, they reset to default on each restart, that leads to the next issue:
- on Android 9 and lower the keymap for DualShock 4 doesn't exist, as such buttons are weird, there are two solutions:
    - root your device and install a magisk module that would copy over the keymap from Android 10.
    - somehow hardcode the right keymap inside the library.

Video: https://drive.google.com/file/d/1BypY1-PXlMIExO7uh1SHNnr_ZLOEDAnL/view?usp=sharing

Overall I like the new library!

**Comment by AlexKhayrullin** [comment]
Thanks :) 

I'm planning on adding more to the library, a couple of functions that make saving/loading less of a hassle (I was trying to handle this via GameMaker and not liking the results) , and a "Tweaks" submenu that would allow, for instance, to disable the L/R trigger button presses, because for instance the Razor Kishi registers pressing left and right triggers as both button presses and axe movements, which is... not good for key mapping, if someone prefers using the triggers (I don't know why anyone would, but hey, at least they should have the option) .

If you have the right key/axis values, I can hard-code them into the library as a selectable preset (I am also tempted to do this for the Nintendo Switch Pro controller which, just like the DualShock 4, is only natively supported starting with Android 10) , but I don't know whether this is a big priority. Also, I don't have an Android 9 device, unless the old smartphone I used to test the game with (and that I recently lost somewhere in my apartment :( ) runs it.

**Comment by nkrapivin** [comment]
[kl_files_a10.zip](https://github.com/overbound/SonicTimeTwisted/files/5267883/kl_files_a10.zip)

Here are all the Sony keylayout files from Android 10.
Product 0x05c4 - Dual Shock 4 V1
Product 0x09cc - Dual Shock 4 V2
Product 0x0ba0 - Dual Shock 4 USB Dongle (basically a weird bluetooth adapter that's hardcoded to work with a Dual Shock)
Product 0x0268 - Dual Shock 3

**Comment by AlexKhayrullin** [comment]
I just watched your video (I couldn't before, I was working) and WOW, is the game slow :( . Now I want to find my old phone even more, I am really afraid this is something I did... in the meantime, can you please test an earlier commit with the same phone, this is the last commit before I started adding any Java code, this one: 9c858a049cf6168dbf6793c1b0aba037ec1d9c5c , and show/tell me whether the game is still just as slow? Because slowdowns were the reason I trashed my previous attempt at gamepad support :( .

Aside from that, is your issue with the PS4 controller simply that labels are weird? Does it work otherwise? Because if it's only a matter of labels, then cool, I can hardcode alternate labels as one of the tweaks in the submenu I mentioned earlier. I also found out there were similar files for Nintendo controllers, so I might cover them too while I'm at it.

Meanwhile, I got a request I'm very much inclined to fulfill: one to add compatibility for two Joy Cons at once :) . That will be interesting.

**Comment by nkrapivin** [comment]
Is your issue with the PS4 controller simply that labels are weird?

kinda yes. (X) button on the controller is mapped to (TRIANGLE) and so on.


(le email)
I just watched your video (I couldn't before, I was working) and WOW the game is slow!

my phone is pretty slow in general :p Redmi models with A at the end are very low budget ones. Also Android export module has a huge problem with surfaces, since changing rendering context takes time, surfaces are very slow.
But hey, it has VK, Telegram, Discord, and it can call, what else do I need? I have a PC for games.

**Comment by AlexKhayrullin** [comment]
Finally done!

The library is integrated, and incompatibilities with some gamepads (which are more or less fringe cases, except for Joy-Cons) can be remedied by using the hardware mapping tool which is now also part of the STT source code.
