### ISSUE TITLE
MetroMayhemZone

### ISSUE THREAD

**Issue by HexagonalX** [overbound/SonicTimeTwisted#44]
I was thinking of adding back the Unused Metro Mayhem Level and I wonder if you would be okay with it? If yes then you can close this, also i might need some help with the caterpillar badnik for said zone

**Comment by overbound** [comment]
You are more than free to make a branch that restores Metro Mayhem and distribute builds of the game with the level in tact. I don't know that we will add it to the the official build though. I won't rule it out 100% but the mishmash of graphical styles when compared to the rest of the game and the added amount of overhead from another zone are reasons why I probably won't make it official.
