### ISSUE TITLE
Game is almost completely broken in GMS2 Version 2.2.3.436

### ISSUE THREAD

**Issue by TheMCNerd2017** [overbound/SonicTimeTwisted#48]
As of GameMaker Studio V2.2.3.436, the game is almost completely broken. Below is a list of the various errors and oddities I got when testing out the game. Note that many of these errors and oddities did not show up in older versions of GameMaker Studio 2 (Pre 2.2.x versions, like 2.1.5). Also, sorry if I'm not allowed to post issues here on this repository, I didn't know where to report these major bugs and I haven't seen any discussion on these bugs. I'm also sorry for making a large issue report, I didn't want to make several issues for each individual bug.

As soon as the game starts up, an error message relating to a surface comes up. It can be ignored, but will come up every step essentially making the game unable to be started. Below is the specific error. Note that sometimes the game will last a few seconds before showing the error, making me think that this may be a race condition.
```
FATAL ERROR in
action number 1
of  Step Event0
for object objTitleLighting:

Trying to set a surface target that does not exist.
 at gml_Object_objTitleLighting_Step_0 (line 13) -        surface_set_target(tt_surface);
```
After putting in a very quick fix to bypass the error and get to the menus, I found that going to the Save Select screen crashes the game instantly, with the following error message.
```
FATAL ERROR in
action number 1
of Alarm Event for alarm 0
for object objSaveSlot:

unable to convert string "" to number
 at gml_Object_objSaveSlot_Alarm_0 (line 3) - futureLevels[0]=real(base64_decode(ini_read_string(LEVELS, aAA1_f, false)));
```
Attempting to go to Galacnik Gauntlet Zone through the level select displays another error message relating to surfaces.
```
FATAL ERROR in
action number 1
of Create Event
for object objFinalBossBackground:

Unbalanced surface stack. you are trying to pop a surface that has not been set.
 at gml_Object_objFinalBossBackground_Create_0 (line 9) - surface_reset_target();
```
Going to any other level through the Level Select results in the game freezing for a few seconds, then instantly closing with no error messages coming up.

I was able to enter special stages successfully through the level select without any issues though, however these strange things happened when doing the normal lose conditions (game was soft-locked and required me to restart when these happened):

![Runner_2019-08-09_18-04-28](https://user-images.githubusercontent.com/25375242/62811677-9490eb00-bad0-11e9-9740-9de80f2a3f9f.png)
![Runner_2019-08-09_18-05-57](https://user-images.githubusercontent.com/25375242/62811690-9ce92600-bad0-11e9-97e6-274e77cc3d31.png)

Note that winning the special stage you're playing works perfectly, the menu comes up like it's suppose to and functions correctly. Attempting to pause results in the game soft-locking on a black screen.

I also managed to get both the main menu and level select to come up, though only the main menu was receiving input.

![Runner_2019-08-09_18-02-23](https://user-images.githubusercontent.com/25375242/62811661-8216b180-bad0-11e9-94e0-6b06128b77fa.png)

There may be more issues that I have not encountered, so making the game fully compatible and fixing the issues might be difficult. While you can use older versions of GMS2 and GMS1 to avoid the issues mentioned, GMS1 does not receive any more support from YoYo Games, and GMS2 could receive a forced update at any time that makes you use the latest version of the program.

**Comment by VectorSatyr** [comment]
Thank you for sharing this with us.

In the future, please know that it is customary and expected to make several independent tickets for each bug encountered. This helps us track individual fixes and allocate available resources as needed.

Please also know that Sonic: Time Twisted was not designed for compatibility with Game Maker Studio 2, and that it may take some time for us to fully address them given our current priorities.

**Comment by TheMCNerd2017** [comment]
OK, I'll make independent tickets in the future when encountering several issues. I also didn't know that Sonic Time Twisted was never meant to work with GMS2, so thanks for telling me.
Should I close this issue or leave it open?

**Comment by VectorSatyr** [comment]
We'll leave it open so it's still in our slate.

Thank you again for your contribution.

**Comment by VectorSatyr** [comment]
Updating the game to GMS2 is a desirable goal, but is out of scope for this repository. Another repository can be created in order to port the game to GMS2.
