### ISSUE TITLE
PPZ Galacnik: two noses

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#59]
![image](https://user-images.githubusercontent.com/2079839/89087784-2529a080-d39e-11ea-9ac6-82f84ebc87dc.png)
During the fight against Galacnik, he sometimes appears with two noses.

**Comment by VectorSatyr** [comment]
Better screenshot:
![Screenshot 2020-07-31 16 36 47](https://user-images.githubusercontent.com/15187586/89088286-495c9180-d34c-11ea-851b-13ad6a3f2aa4.png)

**Comment by AlexKhayrullin** [comment]
It might have been a cache issue (for the context: sometimes, building one branch right after having built another can cause some unwanted cache reuse unless the cache is explicitly cleared) . For the record, both Galacnik's sprite and the one for his nose (the nose is also present on Galacnik's sprite itself) are cropped on the rebuild branch, hence have a different size.

I managed to accidentally reproduce it by building the rebuild branch after building the master branch and forgetting to clear the cache.

**Comment by AlexKhayrullin** [comment]
Also, earlier today when I switched branches and forgot to clear the cache, this happened:

![image](https://user-images.githubusercontent.com/2079839/89112510-5bcdec80-d46c-11ea-8995-0e2ad48ab805.png)

It looks like there issues can get pretty random.
