### ISSUE TITLE
Reduced Flashing option crashes the game.

### ISSUE THREAD

**Issue by nkrapivin** [overbound/SonicTimeTwisted#64]
![image](https://user-images.githubusercontent.com/33228822/91636953-0ca0ba80-ea1e-11ea-94d6-40758c57e83d.png)

It's happening because `menu_part_videooptions_actions` script is trying to reference `objMenu.flashing_reduced`, when in fact it's an `objScreen` variable, and at line 92 in the switch-case it actually does `switch (objScreen.flashing_reduced)`

Soooo probably just a typo...?

**Comment by AlexKhayrullin** [comment]
I prepared a menu option as preparation for #49, but didn't make the feature itself yet.

**Comment by nkrapivin** [comment]
Please reduce red rectangle flashing in the save select screen btw.
If you leave the game window for about 20 seconds, rectangle trail stays on my monitor until you turn it off and let it rest for 10 minutes.

**Comment by nkrapivin** [comment]
Fixed in https://github.com/overbound/SonicTimeTwisted/commit/ae0d54057b848d24e538424002eafffa0329b5f9
Closing the issue, thanks!
