### ISSUE TITLE
Replace existing images with text on them with actual text drawing

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#65]
In order to make the game possible to fully localize, some pictures need to be replaced with uses of draw_text with appropriate fonts:

- "Yes", "No", "No Save", "Past", "Future" and other strings on the save selection screen.
- Metal Sonic's lines (also, make use of the opportunity to make the text appear letter by letter like in an RPG textbox, that might be a nice visual effect)
- ... others? The two examples above are the most prominent ones, but there might be more.

**Comment by AlexKhayrullin** [comment]
Replaced the Metal Sonic lines. @nkrapivin has done the rest.
The present/past signposts are covered in #80 .

So that's all of them.

**Comment by AlexKhayrullin** [comment]
Reopening because one sprite still remains: the "Game Over" label.

**Comment by nkrapivin** [comment]
`string_upper` only works with A-Z letters afaik:
https://docs.yoyogames.com/source/dadiospice/002_reference/strings/string_upper.html

**Comment by AlexKhayrullin** [comment]
It worked with Russian letters too, but good point, I'd better remove string_upper and just make the strings uppercase to begin with.
