### ISSUE TITLE
[SUGGESTION] A Discord server for all Overbound games?

### ISSUE THREAD

**Issue by nkrapivin** [overbound/SonicTimeTwisted#68]
Like, for Sonic Time Twisted, Triple Trouble and No More Robots?

PS: SSL certificate on https://overboundstudio.com/ has expired ~150 days ago.

**Comment by AlexKhayrullin** [comment]
Sonic Triple Trouble 16 Bit is not made by Overbound, but by Noah Copeland.

**Comment by nkrapivin** [comment]
Oh, sorry. It was on the website so I guess I mistook it.

**Comment by Wingzzzzy** [comment]
I can make one for him as someone who knows discord in and out
