### ISSUE TITLE
[Android] Pressing "Quit" in the main menu doesn't actually quit the app.

### ISSUE THREAD

**Issue by nkrapivin** [overbound/SonicTimeTwisted#70]
Since GM:S 1.4.17xx, game_end() no longer quits the app on mobile platforms.

On iOS it does nothing, on Android it puts the app into background.

YoYo thinks that Android is smart enough to decide if it should kill the app or not.

So, maybe remove the Quit button on Mobile?

UPD: Same with consoles, and HTML5.

**Comment by AlexKhayrullin** [comment]
Just leave it on computers. Got it.
