### ISSUE TITLE
Some elements that used to flash don't anymore

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#71]
Probably as a consequence of me adding and then removing a 30FPS mode (which I thought could improve performances on older Android phones) , some elements that used to flash no longer do.

What I've seen so far: "3 2 1 GO" after the race against Metal Sonic starts; appearing blocks in AAZ Past, maybe the lights in the background of AAZ future, I'm not sure.

**Comment by nkrapivin** [comment]
"3 2 1 GO" doesn't flash because User Event 15 toggles flashing... and you've removed the `with (all) event_user(15);` line when removing 30 FPS mode. :p

Maybe some other objects rely on it idk the project file is huge and GMS1 IDE is slow.

**Comment by AlexKhayrullin** [comment]
Yup, that's exactly what happened ^^'

I thought I'd restored all of them, but apparently not...

**Comment by AlexKhayrullin** [comment]
After combing through the project (not manually though, but by searching the string "<event eventtype="7" enumb="25">" in the entire project with Notepad++) , it appears that the following objects are affected. Some of these I've seen, some I haven't, or maybe haven't paid attention: 

- objAA1BossLaser
- objAAFutureBack
- objAALampLight
- objArrowChild
- objArrowParent
- objBigBombBadnik
- objDDFallingPlatformSpawed
- objDDLeaf
- objEggWalker
- objFallingLogVanish
- objFallingPlatform
- objFFDropSpike
- objFinalBossFireball
- objFinalBossLaser
- objFireball
- objFireFlyLightShot
- objGalanikEyeShine
- objHiddenSpring
- objInvisiblePlatform
- objMetallixLaser
- objMetallixPlatform
- objMetalSonicCharge
- objOstrichDibris
- objPaddleTop
- objPPBossDisapearPlatform
- objPPGalanikLaser
- objRingDroppedFinalBoss
- objRoboRex
- objShieldWind
- objSpark
- objSquibot
- objSSMessages
- objSSPlayer
- objSSRingFly
- objVV1BossShield

I did a first pass, removing the events and putting the old code back from master, but I might have missed some.
I'll do a second pass later, using Meld to compare these objects.

**Comment by AlexKhayrullin** [comment]
Second pass done.

Will now test all these objects to make sure they flash in-game.

- [ ] objAA1BossLaser
- [ ] objAAFutureBack
- [ ] objAALampLight
- [ ] objArrowChild
- [ ] objArrowParent
- [ ] objBigBombBadnik
- [ ] objDDFallingPlatformSpawed
- [ ] objDDLeaf
- [ ] objEggWalker
- [ ] objFallingLogVanish
- [ ] objFallingPlatform
- [ ] objFFDropSpike
- [ ] objFinalBossFireball
- [ ] objFinalBossLaser
- [ ] objFireball
- [ ] objFireFlyLightShot
- [ ] objGalanikEyeShine
- [ ] objHiddenSpring
- [ ] objInvisiblePlatform
- [ ] objMetallixLaser
- [ ] objMetallixPlatform
- [ ] objMetalSonicCharge
- [ ] objOstrichDibris
- [ ] objPaddleTop
- [ ] objPPBossDisapearPlatform
- [ ] objPPGalanikLaser
- [ ] objRingDroppedFinalBoss
- [ ] objRoboRex
- [ ] objShieldWind
- [ ] objSpark
- [ ] objSquibot
- [ ] objSSMessages
- [ ] objSSPlayer
- [ ] objSSRingFly
- [ ] objVV1BossShield

**Comment by AlexKhayrullin** [comment]
Fun fact: objAALampLight has never been flashing due to a bug.
Once fixed, the coded flashing that made the alpha go between 1 and 0.5 was too distracting, so I dialed it back to 0.75-0.5

**Comment by AlexKhayrullin** [comment]
Tested all those I could, I have a feeling like objGalanikEyeShine isn't actually used. All other objects are fixed.
