### ISSUE TITLE
Unexpected behaviour when using YYC.

### ISSUE THREAD

**Issue by nkrapivin** [overbound/SonicTimeTwisted#73]
The title.

Since the platformer engine was written by @VectorSatyr, I tried his SonicForGMS example, but it worked just fine, even the oldest one I could find in the git history ran just fine.

So I have no idea why's it broken.

**Comment by AlexKhayrullin** [comment]
IIRC, there was a situation where slopes could work correctly either on PC YYC or on Android YYC, but not both.

**Comment by nkrapivin** [comment]
That is exceptionally weird, since YoYo prefers to use the same clang++ compiler everywhere they can.
The only exception is consoles, on consoles they use whatever the manufacturer gives.

**Comment by nkrapivin** [comment]
Just tried, Android YYC is also broken.

**Comment by VectorSatyr** [comment]
> Since the platformer engine was written by @VectorSatyr, I tried his SonicForGMS example, but it worked just fine, even the oldest one I could find in the git history ran just fine.

Sonic For GMS does quite work the same way; it can be considered a successor or a very distant cousin.

I am also unsure what is different about the YYC compilation that causes slope collision to work differently than when using the Virtual Machine.

**Comment by nkrapivin** [comment]
I suppose the guilty script is `player_get_terrain_angle`.

**Comment by nkrapivin** [comment]
ARGH, why YYC is so hard.

**Comment by nkrapivin** [comment]
![image](https://user-images.githubusercontent.com/33228822/94347719-f18e8e00-004f-11eb-9ac1-29b7c968c4f9.png)

okay `player_get_terrain_angle` is innocent, did a test, got x1/y1/x2/y2/expected angle from VM and tried to calculate the angle on YYC, expected angle matched the YYC angle.

**Comment by nkrapivin** [comment]
![image](https://user-images.githubusercontent.com/33228822/94356606-e2d4c500-00a9-11eb-835a-81d98e1f21e1.png)

huh, it always snaps between 0 and 270?

**Comment by nkrapivin** [comment]
ookay, `player_floor_transfer` returns `false` on YYC, so the object still thinks we're on a regular platform.
that causes everything else to kwek out.

**Comment by nkrapivin** [comment]
How curved slopes in STT are different from slopes in SonicForGMS?

**Comment by VectorSatyr** [comment]
@nkrapivin @AlexKhayrullin Please do a thorough test of the latest commit from origin/rebuild.

**Comment by nkrapivin** [comment]
It fixed the slopes!
I've noticed just now that Future/Past posts are broken
![image](https://user-images.githubusercontent.com/33228822/94372440-d9357680-0116-11eb-8253-a24b1f7b2881.png)
(Sonic just freezes there)

I'll try to fix that myself.

Thank you!

**Comment by nkrapivin** [comment]
Okay here's the fix for time posts:
- open `objTimePost`
- open the Step event (and the only code block in it)
- replace `return something();` with `something();`

You can't return from an event, but for some reason, if you try, the expression in the return statement will be evaluated on VM.
But since YYC events are `void` functions, they can only `return;`, that means whatever was in the return statement will be cut off.

yeah it took me hours to find.
I can commit that fix to my surf-fix branch and make a PR.
It'd be nice to have that fix in origin/rebuild too!

**Comment by nkrapivin** [comment]
After playing STT + #81 (YYC) for a while I didn't notice any huge issues. (at least obvious YYC bugs)

So I'll close this issue for now.
