### ISSUE TITLE
Localization: Past and Future signposts

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#80]
No way we're replacing the graphics with text as part of #65 , they're too iconic.
However, it would be cool if the graphics with the writings could be replaced depending on the chosen language, like the fonts are.

**Comment by nkrapivin** [comment]
https://docs.yoyogames.com/source/dadiospice/002_reference/game%20assets/sprites/sprite_replace.html

**Comment by AlexKhayrullin** [comment]
Made a PR that includes a Russian version of the signpost, which could benefit from someone better at pixelart reworking it :)

I also made a much French version for when we'll have that localization:
![image](https://user-images.githubusercontent.com/2079839/101245966-06a32f80-3719-11eb-9014-74dfd86a8077.png)

**Comment by romulok77** [comment]
> Made a PR that includes a Russian version of the signpost, which could benefit from someone better at pixelart reworking it :)
> 
> I also made a much French version for when we'll have that localization:
> ![image](https://user-images.githubusercontent.com/2079839/101245966-06a32f80-3719-11eb-9014-74dfd86a8077.png)

if you wish you can use one of these

![alexPost](https://user-images.githubusercontent.com/58532222/101282524-816d5880-37b4-11eb-950c-2e8ca8510658.png)
![alexPost1](https://user-images.githubusercontent.com/58532222/101282525-829e8580-37b4-11eb-9390-1509bb74ff07.png)
