### ISSUE TITLE
[Feedback]Gyroscope controls in Special Stages

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#82]
Since a dev build "leaked", I got some comments about gyroscope controls in Special Stages.

Please do share your opinions here, and don't worry if they clash, I like making stuff configurable. Case in point: right now, you can configure different thresholds or even revert to the simple joystick/DPad.

**Comment by LucasMegaStriker** [comment]
I think the main problem is the dead zone for the movement stick. If at least a bit more of this dead zone got increased, it wouldn't be so difficulty to handle.

**Comment by AlexKhayrullin** [comment]
In this case, I'll add configurable dead zones to both versions of the joystick (4-directional in regular stages and 2-directional in special stages) . Same deal as with the gyros themselves: I'll make them configurable, but I do expect feedback to tell what setting should be the default.

As of the weird issue with the menu @VectorSatyr mentioned, I'm aware of that :(
Worst part is, it didn't happen with my first attempt at recoding the menu, which was admittedly horribly coded and didn't look that great. Anyhow, it's on my TODO list.

**Comment by AlexKhayrullin** [comment]
The two fixes I promised are implemented (sorry it took me so long) .

**Comment by AlexKhayrullin** [comment]
Having added the fixes and, with @VectorSatyr 's help, set default values to something usable, I consider this issue done.
