### ISSUE TITLE
Touchscreen controls dissapear after death

### ISSUE THREAD

**Issue by LucasMegaStriker** [overbound/SonicTimeTwisted#83]
When Sonic lose a life on any point of the stages (except special stages) and respawn to the next checkpoint, the touchscreen controls dissapears and don't show up again, and only return when the game resets.

Not sure if the same is happening on other mobile devices, mine is a Xiaomi Pocophone F1, and the game runs perfect. Just that possible bug is messing with the gameplay.

**Comment by romulok77** [comment]
Always has been

**Comment by AlexKhayrullin** [comment]
Enabling/disabling controls wasn't properly implemented in the dev build.
I enabled it as often as I could with my previous commit, but it led to the controls appearing when not needed (during score countdowns mostly) . I'm currently working on this, and should be done as soon as I replay the entire game on mobile with couple fixes here and there.
