### ISSUE TITLE
Improve some sprites

### ISSUE THREAD

**Issue by romulok77** [overbound/SonicTimeTwisted#86]
- This is certainly not very important. But looking at the code files and playing, I realized that the game uses the same sprites as the 2017 version, so I think some sprites should go through some small changes, such as: one or two frames more, and improve some. so i did it to give an example, if it is feasible I can send others later to evaluate and if it is your taste to add to the game

 After
![sprSonicLook_2](https://user-images.githubusercontent.com/58532222/94980831-ba165a80-0503-11eb-8039-c60aae32d057.png)

 Before
![sprSonicLook_0](https://user-images.githubusercontent.com/58532222/94980832-bb478780-0503-11eb-9453-a8f9c5f9a6db.png)

with just a few changes the sprite just got a little better in my opinion.

- This one I just added a sprite at the end where Sonic looks at the emerald and extends his hands under it. rsrsrs. and I fixed a defect that he had on his left leg in two frames

![sprSonicSSEnd3](https://user-images.githubusercontent.com/58532222/94980878-0eb9d580-0504-11eb-8b5c-1812fc4febd7.gif)

- In FFZ, when the characters slide on the ice floor, everyone uses the damage sprite, so at that moment I added another frame, so they slip by waving their arms aaaahhh. I think about adding a third party

![sonic hurt](https://user-images.githubusercontent.com/58532222/94981101-e16e2700-0505-11eb-8f4a-f52f994a4b33.gif)

- This is the skateboard used in FFZ, it won nothing, just a new face, a reference to sonic statue from japan

![skateboard_y](https://user-images.githubusercontent.com/58532222/94981003-fdbd9400-0504-11eb-8975-e3891759ba62.gif)

- Here i added three more frames, so that sonic doesn't have to slide statically

![sprSonicSnowboaty](https://user-images.githubusercontent.com/58532222/94981348-edf37f00-0507-11eb-9272-4618e256cf82.gif)

 at the moment I just did this, and sonic will move his legs later, in this case sonic move his arms to balance himself, and his feet are attached to the skateboard by handles, and maybe I have to narrow that huge eye

- I'm on my phone and I have no idea how the git page will look on the computer. so that was it for now, it was just to set an example and all the characters should win it, there are still others to do and also improve the ones I have already done. If you think these small changes are feasible, it would be nice

**Comment by romulok77** [comment]
Se interessou tenho links para cada:

https://i.ibb.co/BzGcLnp/skateboard-k.png
https://i.ibb.co/GFGLpd0/spr-Sonic-SSEnd3.png
https://i.ibb.co/G7bKhr7/spr-Sonic-Snowboat.png
https://i.ibb.co/cXkKnWd/sonic-hurt1.png
https://i.ibb.co/HKvgfq5/spr-Sonic-Look-ssdd.png

**Comment by nkrapivin** [comment]
> Interested? I have links for each:
> 
> https://i.ibb.co/BzGcLnp/skateboard-k.png
> https://i.ibb.co/GFGLpd0/spr-Sonic-SSEnd3.png
> https://i.ibb.co/G7bKhr7/spr-Sonic-Snowboat.png
> https://i.ibb.co/cXkKnWd/sonic-hurt1.png
> https://i.ibb.co/vPpy34W/spr-Sonic-Look-ssd.png
> 
> all are in the correct size to be tested in the game

Do you have Discord? I can make an experimental build w/ ability to replace sprites without needing to rebuild the game and send it to you.

**Comment by romulok77** [comment]
Yes: Romulo #2261

**Comment by romulok77** [comment]
> > Interessado? Tenho links para cada um:
> > [https://i.ibb.co/BzGcLnp/skateboard-k.png ](https://i.ibb.co/BzGcLnp/skateboard-k.png)
> > [https://i.ibb.co/GFGLpd0/spr-Sonic-SSEnd3.png ](https://i.ibb.co/GFGLpd0/spr-Sonic-SSEnd3.png)
> > [https://i.ibb.co/G7bKhr7/spr- Sonic-Snowboat.png ](https://i.ibb.co/G7bKhr7/spr-Sonic-Snowboat.png)
> > [https://i.ibb.co/cXkKnWd/sonic-hurt1.png ](https://i.ibb.co/cXkKnWd/sonic-hurt1.png)
> > https://i.ibb.co/vPpy34W/spr-Sonic-Look-ssd.png
> > todos estão no tamanho correto para serem testados no jogo
> 
> Você tem Discord? Posso fazer um build experimental com capacidade de substituir sprites sem precisar reconstruir o jogo e enviá-lo para você.

Yes: Romulo #2261

**Comment by romulok77** [comment]
I recorded a small video without much editing, just to show a little progress in some sprites, and also in the PT-BR translation I am trying to do, this is just a sample so these will receive a touch up and others will be slightly improved. 

See: https://drive.google.com/file/d/12njYPdCjHTsz-N9M4Orx7rThaQDgNA_p/view?usp=drivesdk

when it's all done maybe I make a comparison
