### ISSUE TITLE
Integrate Bennascar's reshaded boss sprites

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#89]
Bennascar had contacted me to suggest edits to two boss sprites, and indeed, the added shading on them is an improvement without going too far (he made it a point to only use the colors that are already present on the sprites in question) .

![VVZ_boss_damaged](https://user-images.githubusercontent.com/2079839/95504952-2be41d80-09b6-11eb-8229-567917b3686e.png)
![VVZ_boss](https://user-images.githubusercontent.com/2079839/95504957-2c7cb400-09b6-11eb-80de-24223ec958db.png)
![RRZ_boss](https://user-images.githubusercontent.com/2079839/95504958-2d154a80-09b6-11eb-896b-45c78987ff6b.png)

**Comment by VectorSatyr** [comment]
Note that if these sprites are added to the game, he will need to be credited in some way.
