### ISSUE TITLE
Things left to do with the end credits

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#90]
The end credits have been re-coded to make them scroll and easier to add to.

The following things are still on the TODO list:

- Make the scrolling smooth. There should be a way for credits text (and this text alone) to take decimal parts of the y coordinate into account. Because while using integer coordinates makes for a clearer picture, it can cause the scrolling speed to appear uneven.
- Depending on how many names are added, make the scrolling slightly faster. The background scrolls one time too many as of right now. 
- Dynamically add the name(s) of the author(s) of the currently used localization, if one is used. While adding all of them seems to be a better choice, it takes away all control from us over the previous point: install just the base game and the credits will scroll normally, add 10 of them, and they will scroll way too fast to be readable.
- Decide on a crediting policy (obviously, all contributors will receive credit, but it's the organization of the end credits that should be discussed: do we add people to existing sections? Do we create new ones?) .

**Comment by VectorSatyr** [comment]
- [ ] Make scrolling smooth
- [ ] Adjust scrolling speed relative to total name count
- [ ] Dynamically add author(s) name(s) of currently used localization, if used
- [ ] Approve Crediting Policy

**Comment by AlexKhayrullin** [comment]
After some recent discussions, here's what has been decided when it comes to the crediting policy:

- Since the naming scheme 'First Name Last Name "Nickname"' has been established as a reference to Sonic 2, the reference will be reinforced by replacing quotes with parentheses.
- The opening crawl will be altered by replacing full names by simply nicknames, with two exceptions, per their request. Also, per another team member's request, their nickname will be updated in both the 1.1 branch and the master branch (so if a release 1.0.4.1 pops up, that's the only difference, not newsworthy, that's just me following Git's best practices :) ) .
- The contents of the end credits will remain as they are, the only exception being that quotes will be replaced with parentheses.
- The game's original credits as of 1.0.4 will be off limits and not subject to change, these are the names of the original dev team and as such, they are set in stone. Names of the people who contributed to the project after it went open source will go into a new section in the credits, into subsections dedicated to different areas (development, art...) .

**Comment by AlexKhayrullin** [comment]
OK, so it appears that due to how GMS handles drawing fonts, drawing them only at rounded coordinates, I can't actually make scrolling smooth except at certain precise speeds. The one used right seems OK, but still leaves some time between the credits' end and end scene.

In order to hide the issue, what I can do is use the credits' length to calculate the time objCredits will wait before the credits start, to shorten the wait time at the end.

**Comment by AlexKhayrullin** [comment]
So... I did my best to improve scrolling based on the credits' length, but there's only so much you can do when GMS draws text at only integer coordinates, and I don't want the credits to look like they're constantly skipping.

The rest is done, and I tr()-ified the ending text, which was completely forgotten until now.
