### ISSUE TITLE
[Feature Request] Sound settings?

### ISSUE THREAD

**Issue by nkrapivin** [overbound/SonicTimeTwisted#92]
The only actual "volume" related code I saw is in the objProgram where it sets master audio gain to 0.75.

Maybe make an option to toggle SFX/BGM and set the audio volume?

**Comment by VectorSatyr** [comment]
Go for it. It honestly should have been a feature from the very beginning, but we never got around to it.

**Comment by AlexKhayrullin** [comment]
@nkrapivin What is left for this issue to be closed?

You asked for the sliders to be able to scroll faster by holding left/right, I hadn't forgotten that :) . Is there anything else?

**Comment by nkrapivin** [comment]
No, I'll translate the sound settings to Russian and close the issue.
