### ISSUE TITLE
Replace sprites

### ISSUE THREAD

**Issue by romulok77** [overbound/SonicTimeTwisted#93]
....

**Comment by VectorSatyr** [comment]
@romulok77  Your video requires a request for access.

**Comment by romulok77** [comment]
> @ romulok77 Seu vídeo requer um pedido de acesso.

sorry i didn't know, i'll fix it.

**Comment by romulok77** [comment]
> @ romulok77 Seu vídeo requer um pedido de acesso.

Tente agora

**Comment by VectorSatyr** [comment]
@romulok77 It works now. Thanks.

**Comment by AlexKhayrullin** [comment]
Reopening, since I've closed the PR.

**Comment by romulok77** [comment]
- Sonic: 
. Sonic Look: changed the head and + 1frame . Sonic Cliff: Corrected one frame and deleted the last frame.
 . Sonic stand rotate: thorn, glove and eyes adjustment and some frames
 . Sonic SSEnd: leg correction in some frames, and sonic extends his arms in the last frame . 
Sonic SS Stand: only fixed one leg. .Sonic SSJump: I used the tails sprites, recolored and inverted the order, I thought that this jump effect on the SS would be better Sonic snowboard: correction of the last two frames. 
.Sonic dead and drow: changed the eyes when sonic dies and changed the drowning frame to a frame that already existed.

Super Sonic:

.Super Rotate: changed the spines and gloves.
.Super crouch: little changed the spines.
.Super dead and drow: changed the eyes and thorns in common death and used an existing framework in death by drowning.
.Super float: changed the spines, placing them upwards.
.Super snowboard: I just fixed some things out of place
.Super get air: rose the thorns.
.Super 3d turn: changed the spines up

Tails:
Tails Run '1': changed the eyes, now it looks more like the common tails sprites
.Tails Run '2': when tails reaches maximum speed a frame was added, the tail rotation and also the eyes changed.
.Tired Tails: Altered eyes and mouth when tails get away from flying.
.Tails standrotate: adjusted the rotation by correcting 2 frames that made the animation go wrong.

Knuckles:
. SSEnd: changed the ending, so he now extends his hands to collect the emerald 

.SSJump: The same thing as sonic was done, but obviously with the colors of the knuckles

**Comment by romulok77** [comment]
- the rejected changes were withdrawn and I replaced the originals

-SonicSSend: I just changed my head a little in the last frame

- sprSonicdead,Superdead: you said you would use the original sprites for sonic drowning, so I left the sprites that already existed (except for the supersonic, as it changed the spines) and put the altered one together. So if you decide to rethink about it, use the first court for common deaths.

- tailsrun: I left the tails' feet shaking as it should be, the animation hasn't changed. that was it?

-sonic rotate and super rotate: I put sonic mouth where it had been removed.

suggestion: 

-tailsrotate: the frame in which tails looks at the screen always looks below 1 pixel, but looking at it, this came from the original STT sprites. even if I change several things it continues like this, so I ask that for now leave it like this, I'm still trying to see what the problem is. and when i find it, i ask alex to change this unique frame.

**Comment by romulok77** [comment]
- Tails run: in the last 3 frames(fast animation) a last change was made in the tails, yes they are of sonic mania.

- Tailsstand rotate: it doesn't look like the tails board looks at the player a pixel down.

- Supersonicstandrotate: more changes made to the spines in some frames.

- supersonic floating: altered the spines in some frames.

- SuperSonic3dturn: aligned height in some frames and change in spines

- Sonic snowboard: small changes in the last 2 frames.

- Supersoniccrouch: looks a bit like the super sonic from in sonic 3.
