### ISSUE TITLE
Suggestion: add a shield icon in Special Stages

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#96]
Something that might be useful in special stages is to add a fourth line below "Score", "Time" and "Rings"  showing the currently equipped shield. I think that adding the shield to the HUD in the top left instead of placing it elsewhere on the screen (like in the middle or something) would serve to draw less attention to it, maybe serving as an indication that the shield does not affect the gameplay in Special Stages and is a reward instead.

That way, the player knows what kind of shield they would have after returning from a Special Stage, and that way won't repeat the mistake I constantly do: pick up a Fire or Lightning Shield while the Giant Ring they just went through is underwater. Unless such trickery is intentional :) .

I can draw easily recognizable icons that would be of the same size as the HUD's font to represent the currently equipped shield, that way they fit in visually.

But in the meantime: discuss!

**Comment by VectorSatyr** [comment]
On that note: I'm not sure, but I think retrying in the Special Stages causes you to lose the shield you had when entering it. That should probably be fixed, if true, but I haven't tested it enough.

Yes, having the currently acquired shield be visible in the HUD somehow would be a very helpful addition.

**Comment by AlexKhayrullin** [comment]
Quick mockup of what I have in mind:

![image](https://user-images.githubusercontent.com/2079839/100550532-497d8700-3283-11eb-9ecd-f4d3d807c918.png)

I drew the icons for all the shields, making them as big as the font, and with the same type of shadow, here they are compared to their pictures as seen on monitors:

![image](https://user-images.githubusercontent.com/2079839/100550546-5c905700-3283-11eb-88b1-e48ab3f2be6c.png)

Comments are welcome :)

**Comment by VectorSatyr** [comment]
I was thinking more an icon in the top-center of the screen, ala-Super Mario World. This works fine, though; in fact, the way it's arranged it may even be kinda nice in normal levels, too.
